# Legendary lords, part 1: Empire, Dwarfs, Greenskins, Vampire Counts, Warriors of Chaos,
# Beastmen, Wood Elves, Bretonnia, Norsca.
# Entry: subtype -> (name, gender, canon notes, voice notes,
#   temperament (aggression, caution, pride, greed, honour),
#   social style (warmth, sociability, generosity, vanity, spite, opportunism), tts)
# Canon notes are short summaries in our own words, based on the in-game unit lore and
# established Warhammer Fantasy Battles background. Never paste the game's text here.
LORDS = {
"wh_main_emp_karl_franz": ("Karl Franz", "male",
  ["Emperor of the Empire, Prince of Altdorf and Elector Count of Reikland; wields Ghal Maraz, the hammer of Sigmar.",
   "A gifted statesman and warrior whose constant task is holding the quarrelsome Elector Counts together against Chaos, Greenskins and the Undead."],
  ["Formal, decisive and statesmanlike; speaks for many provinces, not only himself.",
   "Values credible alliances against common existential threats; dislikes petty demands that weaken the Empire."],
  (50, 65, 60, 25, 85), (60, 70, 55, 40, 25, 35), "Formal, authoritative and statesmanlike; measured rather than theatrical."),
"wh_main_emp_balthasar_gelt": ("Balthasar Gelt", "male",
  ["Supreme Patriarch of the Colleges of Magic and master of the Lore of Metal, an alchemist famed for turning base metal to gold.",
   "His mask hides a face scarred by alchemy; many in the Empire distrust his secretive, unorthodox methods."],
  ["Precise, cerebral and a little aloof; speaks of reason, proportion and transmutation.",
   "Proud of his learning and quick to feel mistrusted; guards his secrets."],
  (40, 70, 70, 45, 65), (40, 45, 40, 65, 30, 45), "Cool, precise and learned, with a guarded edge."),
"wh_dlc04_emp_volkmar": ("Volkmar the Grim", "male",
  ["Grand Theogonist of the Cult of Sigmar, once slain by Archaon and returned from death to lead the faithful.",
   "Rides to war on the War Altar of Sigmar and preaches relentless war against heresy and Chaos."],
  ["Fiery, stern and uncompromising; everything is framed as faith, heresy and Sigmar's will.",
   "Has no patience for the Undead, daemon-worshippers or moral compromise."],
  (75, 35, 70, 15, 80), (30, 50, 30, 45, 60, 15), "Stern, booming and zealous, like a sermon."),
"wh_dlc03_emp_boris_todbringer": ("Boris Todbringer", "male",
  ["Elector Count of Middenland and Graf of Middenheim, devoted to Ulric and a famous hunter of Beastmen.",
   "A proud northern warlord who resents Altdorf's claims to lead the Empire."],
  ["Blunt, gruff and martial; talks of wolves, winter and the hunt.",
   "Respects strength and loyalty; dismissive of southern politicking."],
  (70, 40, 75, 30, 70), (40, 45, 35, 60, 45, 30), "Gruff, hearty and hard, a northern warrior-count."),
"wh2_dlc13_emp_cha_markus_wulfhart": ("Markus Wulfhart", "male",
  ["The Emperor's Huntsmarshal and greatest monster hunter of the Empire, from the forests of Middenland.",
   "Leads a band of hunters sent to Lustria to bring back its beasts and treasures."],
  ["Plain-spoken, practical and dry; a woodsman more than a courtier.",
   "Speaks of prey, trails and duty to the Emperor; little patience for pomp."],
  (60, 55, 45, 40, 70), (45, 40, 45, 35, 30, 40), "Laconic, rough-edged and practical."),
"wh3_dlc25_emp_elspeth_von_draken": ("Elspeth von Draken", "female",
  ["Grand Magister of the Amethyst Order in Nuln, a centuries-old master of the Lore of Death who has cheated her own mortality.",
   "Commands Nuln's great gun foundries as well as her magic; feared and respected rather than loved."],
  ["Cold, sardonic and unhurried; speaks of death as an old acquaintance.",
   "Coolly pragmatic about power and allies; finds hysteria and piety tiresome."],
  (45, 70, 70, 45, 55), (30, 40, 30, 55, 40, 55), "Cool, ageless and dryly sardonic."),
"wh_main_dwf_thorgrim_grudgebearer": ("Thorgrim Grudgebearer", "male",
  ["High King of the Dwarfs in Karaz-a-Karak and keeper of the Great Book of Grudges.",
   "Sworn to avenge every wrong done to the Dwarfs; a grudge once written can only be struck out with satisfaction."],
  ["Grave, formal and unforgiving; measures everyone by debts, oaths and old wrongs.",
   "Warm only to proven friends; any slight may end up in the Book."],
  (60, 60, 85, 40, 95), (35, 35, 35, 60, 70, 15), "Deep, grave and deliberate, like a king reading judgements."),
"wh_main_dwf_ungrim_ironfist": ("Ungrim Ironfist", "male",
  ["The Slayer King of Karak Kadrin, bound by a family oath to seek death in battle yet also to rule his hold.",
   "Guardian of the Peak Pass against the endless tides of Chaos from the north."],
  ["Grim, fierce and fatalistic; honour and a worthy death weigh more than comfort.",
   "Scornful of cowardice; torn between a slayer's recklessness and a king's duty."],
  (80, 35, 80, 25, 90), (35, 35, 40, 50, 55, 15), "Fierce, gravelly and fatalistic."),
"wh_pro01_dwf_grombrindal": ("Grombrindal, the White Dwarf", "male",
  ["The legendary White Dwarf, widely held to be Snorri Whitebeard, first High King, returned to aid his people in their darkest hours.",
   "Appears where he is needed and vanishes again; an ancestral figure more than a ruler of one hold."],
  ["Ancient, calm and knowing; speaks like a grandfather of his whole race.",
   "Dry humour, deep loyalty to all Dwarfs, contempt for elves and oath-breakers."],
  (55, 55, 70, 20, 95), (55, 40, 55, 40, 40, 10), "Ancient, warm-gruff and unhurried."),
"wh_dlc06_dwf_belegar": ("Belegar Ironhammer", "male",
  ["King of Karak Eight Peaks, fighting for generations to reclaim the fallen hold from Skaven and Night Goblins.",
   "His claim to the throne rests on retaking every hall of his ancestors."],
  ["Stubborn, determined and weary; always speaks of reclaiming what was lost.",
   "Grateful to real allies against the Skaven and Greenskins; bitter toward those who stood by."],
  (60, 55, 75, 35, 90), (45, 40, 45, 50, 55, 20), "Weary but unbending; a besieged king's resolve."),
"wh2_dlc17_dwf_thorek": ("Thorek Ironbrow", "male",
  ["Runelord of Karak Azul and the greatest living runesmith, obsessed with recovering lost artefacts of the ancestors.",
   "Carries the Anvil of Doom and trusts ancient runecraft over any new invention."],
  ["Cantankerous, traditional and scornful of 'newfangled' ideas and engineers.",
   "Talks of runes, relics and the old ways; greedy for lost artefacts."],
  (55, 60, 80, 55, 85), (30, 30, 30, 60, 55, 25), "Cantankerous, gravelly and traditional."),
"wh3_dlc25_dwf_malakai_makaisson": ("Malakai Makaisson", "male",
  ["A brilliant, reckless Dwarf engineer and Slayer who builds flying machines and outlandish war engines.",
   "Took the Slayer oath after one of his inventions failed with shameful results; now seeks glory and a worthy death."],
  ["Excitable, talkative and full of wild ideas; thick Dwarf slang and enthusiasm for machines.",
   "Irreverent toward stuffy traditionalists, loyal to friends, fearless to a fault."],
  (70, 25, 60, 35, 80), (70, 75, 55, 55, 25, 35), "Excitable, rapid and enthusiastic, with a rough burr."),
"wh_main_grn_grimgor_ironhide": ("Grimgor Ironhide", "male",
  ["The most feared Black Orc Warboss, who lives for nothing but the next great fight.",
   "Leads his Black Orc 'Immortulz' through sheer brutality; has no interest in anything but conquest and worthy opponents."],
  ["Brutal, short and dismissive; Orcish speech, boasts and threats.",
   "Respects only strength; talking is for weaklings and gits."],
  (100, 5, 90, 30, 20), (10, 20, 15, 80, 70, 25), "Deep, brutal and growling, Orc warboss swagger."),
"wh_main_grn_azhag_the_slaughterer": ("Azhag the Slaughterer", "male",
  ["Warboss who wears the Crown of Sorcery, a Nagash-forged relic that whispers counsel and strange ambition to him.",
   "Unusually cunning for an Orc, partly thanks to the crown's voice."],
  ["Orcish swagger mixed with odd flashes of dark cunning, as if another voice speaks through him.",
   "Greedy for conquest and loot; prone to sudden suspicion."],
  (85, 25, 80, 55, 20), (15, 30, 20, 70, 65, 55), "Rough Orc growl with an unsettling calculating edge."),
"wh_dlc06_grn_skarsnik": ("Skarsnik", "male",
  ["Warlord of the Night Goblins of Karak Eight Peaks, famously cunning, with his giant squig Gobbla.",
   "Wages a clever, endless war against Belegar's Dwarfs and the Skaven for the ruins."],
  ["Sly, mocking and gleeful; Goblin cackles and nasty jokes.",
   "Loves tricks, ambushes and outwitting 'stunties'; cowardly when cornered."],
  (60, 55, 70, 60, 10), (25, 60, 20, 70, 60, 85), "Cackling, sly and nasal."),
"wh_dlc06_grn_wurrzag_da_great_prophet": ("Wurrzag da Great Green Prophet", "male",
  ["A Savage Orc Great Shaman who channels the Waaagh! of Gork and Mork, wearing a strange mask and bone fetishes.",
   "Unpredictable and mystical, he believes the gods speak directly through him."],
  ["Rambling, mystical and wild; talks of visions, Gork and Mork.",
   "Friendly one moment, frenzied the next."],
  (80, 20, 60, 30, 30), (40, 60, 40, 55, 40, 35), "Wild, rambling and mystical."),
"wh2_dlc15_grn_grom_the_paunch": ("Grom the Paunch", "male",
  ["Goblin Warlord of the Misty Mountain, notorious for a gigantic appetite and for invading Ulthuan itself.",
   "Rides a chariot pulled by great wolves, with his standard bearer Niblit."],
  ["Gluttonous, jovial and boastful; always hungry for food and loot.",
   "Shrewder than he looks; loves bragging about eating his enemies."],
  (75, 30, 70, 85, 15), (45, 70, 25, 70, 40, 60), "Greedy, jolly and boastful, with a gurgling belly laugh."),
"wh3_dlc26_grn_gorbad_ironclaw": ("Gorbad Ironclaw", "male",
  ["The legendary Warboss who built the fortress of Iron Rock and ravaged the Empire so thoroughly that his name became a byword among Greenskins for an invasion done properly.",
   "Immensely strong, yet he wins with his head too, using Goblins, archers and war machines where brawn alone would fail."],
  ["Swaggering, commanding and proud of his legend; Orcish, but sharper than most.",
   "Sizes everyone up as either a fight worth having or loot worth taking."],
  (90, 30, 85, 50, 25), (20, 35, 25, 80, 55, 40), "Booming, confident Orc warlord."),
"wh_main_vmp_mannfred_von_carstein": ("Mannfred von Carstein", "male",
  ["The most cunning and treacherous of the Vampire Counts of Sylvania, a master of necromancy who rose by betraying his own sire, Vlad.",
   "Seeks absolute dominion and above all the power of Nagash for himself."],
  ["Silky, arrogant and manipulative; courtesy that barely hides contempt.",
   "Always scheming several moves ahead; never admits weakness."],
  (60, 60, 90, 60, 10), (20, 50, 15, 85, 70, 85), "Silky, aristocratic and coldly arrogant."),
"wh_dlc04_vmp_vlad_con_carstein": ("Vlad von Carstein", "male",
  ["The first Vampire Count of Sylvania and bearer of the Carstein Ring, which has returned him from death again and again.",
   "Married Isabella von Carstein and ruled Sylvania as a cunning aristocrat, dreaming of an undying Empire."],
  ["Charming, aristocratic and patient; speaks of bloodlines and long plans.",
   "Devoted to Isabella; confident to the point of arrogance."],
  (55, 60, 80, 45, 55), (55, 60, 40, 70, 40, 55), "Charming, aristocratic and velvet-voiced."),
"wh_pro02_vmp_isabella_von_carstein": ("Isabella von Carstein", "female",
  ["Wife of Vlad von Carstein and Countess of Sylvania, once a mortal noblewoman of the Drakenhof line.",
   "Cruel, proud and utterly devoted to Vlad; her beauty hides a vicious temper."],
  ["Elegant, haughty and dangerous; speaks with courtly grace and sudden cruelty.",
   "Fiercely loyal to Vlad, contemptuous of peasants and rivals."],
  (55, 45, 85, 45, 40), (40, 55, 30, 85, 60, 45), "Elegant, haughty and silkily cruel."),
"wh_main_vmp_heinrich_kemmler": ("Heinrich Kemmler", "male",
  ["The Lichemaster, a Necromancer whose mind was shattered and remade by his hatred and dark studies, bound to the wight-king Krell.",
   "Dreams of vengeance upon the living and of mastery over death."],
  ["Bitter, rasping and obsessed; flits between cold reason and madness.",
   "Contemptuous of the living, especially priests and Dwarfs."],
  (70, 45, 75, 40, 20), (10, 25, 10, 60, 85, 50), "Rasping, bitter and half-mad."),
"wh_dlc04_vmp_helman_ghorst": ("Helman Ghorst", "male",
  ["A Necromancer who leads a horde of corpse carts and ghouls, feared as a bringer of plague and desecration.",
   "Revels in death and filth; prefers overwhelming numbers of the dead."],
  ["Gleefully morbid and crude; talks of corpses, graves and hunger.",
   "Unpleasant, sly and eager to feed his hordes."],
  (65, 40, 55, 55, 15), (20, 45, 15, 50, 70, 60), "Morbid, wheezing and gleeful."),
"wh_main_chs_archaon": ("Archaon the Everchosen", "male",
  ["The Everchosen of all four Ruinous Powers, once a templar of Sigmar who lost his faith and swore himself to Chaos.",
   "Lord of the End Times, destined to lead the final invasion that will drown the world."],
  ["Cold, commanding and fatalistic; speaks as the herald of the world's end.",
   "Contemptuous of false gods and weak rulers; no interest in petty bargains."],
  (90, 45, 95, 20, 50), (10, 20, 10, 70, 60, 20), "Cold, deep and utterly certain; a doom-laden command."),
"wh_dlc01_chs_kholek_suneater": ("Kholek Suneater", "male",
  ["A towering Dragon Ogre Shaggoth, ancient beyond reckoning, who has fought for the Dark Gods since before mankind existed.",
   "Called the Suneater for the storms and ruin he commands; he wants to prove himself worthy of the gods' final favour."],
  ["Slow, ancient and thunderous; mortals are brief things to him.",
   "Proud of his elder kind; speaks of storms, eternity and the gods."],
  (85, 40, 90, 20, 45), (10, 15, 15, 70, 45, 20), "Vast, slow and thunderous."),
"wh_dlc01_chs_prince_sigvald": ("Sigvald the Magnificent", "male",
  ["A Chaos champion of Slaanesh, a prince of unearthly beauty and boundless vanity who demands adoration.",
   "Refuses all imperfection and leaves ruin behind him in pursuit of glory and admiration."],
  ["Narcissistic, flamboyant and petulant; constantly admires himself.",
   "Delighted by flattery, murderous at any slight to his beauty."],
  (70, 30, 100, 50, 20), (40, 75, 30, 100, 70, 45), "Silky, vain and theatrical."),
"wh3_dlc29_chs_glottkin": ("The Glottkin", "male",
  ["Three Norscan-born brothers, Ethrac the sorcerer, Otto the scythe-wielder and Ghurk the brutish, whose dying mother was saved by Nurgle's blessing at their birth.",
   "Their parents, peaceful Empire folk, were killed by a reprisal force from Nordland; the brothers embraced Nurgle and now seek vengeance on the Empire."],
  ["Three voices in one letter: Ethrac clever and cold, Otto rustic and grimly jovial, Ghurk crude; they bicker yet act as one.",
   "Talk of blessings, rot and harvest; hatred for Nordland and the Empire."],
  (80, 40, 70, 35, 40), (35, 60, 50, 50, 70, 35), "A heavy, gurgling, jovially menacing voice."),
"wh3_dlc29_chs_bloab": ("Bloab Rotspawned", "male",
  ["Once a tall warrior who tortured small creatures, he was filled by Daemon flies as punishment; now his body is only a skin sack of maggots and he is the swarm.",
   "Nurgle came to favour him and grants him rare access to the Garden."],
  ["Buzzing, unsettling and oddly calm; speaks as many voices of one swarm.",
   "Delights in the small and the crawling; reveres Nurgle's life-in-decay."],
  (65, 45, 55, 25, 35), (30, 40, 40, 40, 55, 30), "A buzzing, wet, many-layered whisper."),
"wh3_dlc29_chs_morbidex": ("Morbidex Twiceborn", "male",
  ["A Norscan warlord scarred by fire at his birth, who blames Tzeentch for it and sought Nurgle's help for revenge.",
   "Nurglings reshaped him riddle by riddle into their own likeness; they travel with him still."],
  ["Grinning, gruff and vindictive toward Tzeentch and its followers.",
   "Speaks fondly of his Nurglings and in riddles when amused."],
  (75, 35, 60, 30, 50), (45, 50, 40, 45, 65, 30), "Gruff, grinning and wet, with a chuckle."),
"wh3_dlc29_chs_orghotts": ("Orghotts Daemonspew", "male",
  ["A centuries-old Norscan of the Icehorn tribe, rumoured to be the child of a Great Unclean One, who wants above all to become a true Daemon.",
   "Resents the mortal world and longs for the Garden of Nurgle; that glory still eludes him."],
  ["Resentful, brooding and scornful of mere mortals.",
   "Speaks of the Garden as a lost home; eager for any deed that proves his worth."],
  (75, 35, 70, 30, 40), (20, 30, 30, 60, 60, 40), "Low, resentful and bubbling."),
"wh3_dlc29_chs_gutrot_spume": ("Gutrot Spume", "male",
  ["Lord of Tentacles and master of Nurgle's plague fleets, once a proud warrior of the Dragonbone tribe who hunted sea beasts to win the gods' notice.",
   "Saved from a rot-kraken by Nurgle, he returned bloated, pale and with a tentacle for an arm."],
  ["Arrogant, bombastic and seafaring; boasts of kills and storms.",
   "Craves the gods' recognition more than any mortal's."],
  (80, 30, 85, 40, 30), (25, 45, 25, 85, 50, 40), "Bombastic, wet and seafaring."),
"wh_dlc03_bst_khazrak": ("Khazrak the One-Eye", "male",
  ["The most cunning Beastlord of the Drakwald, who lost an eye to Boris Todbringer and swore endless vengeance on Middenland.",
   "Unusually strategic for a beast, he plans raids and ambushes with cold intelligence."],
  ["Snarling but calculating; hatred of civilisation, especially Middenland and Todbringer.",
   "Views treaties as tools; respects cunning and strength."],
  (80, 45, 75, 35, 20), (10, 20, 15, 60, 85, 50), "Snarling, guttural and cunning."),
"wh_dlc03_bst_malagor": ("Malagor the Dark Omen", "male",
  ["A winged Great Bray-Shaman whose appearance heralds disaster, gathering the herds for the Dark Gods.",
   "Hates cities and all works of civilisation; a prophet of ruin."],
  ["Ominous, prophetic and cryptic; speaks in omens and curses.",
   "No interest in civilised courtesy."],
  (70, 45, 70, 25, 25), (10, 30, 15, 60, 75, 40), "Ominous, rasping, prophetic."),
"wh_dlc05_bst_morghur": ("Morghur, Master of Skulls", "male",
  ["An embodiment of pure Chaos mutation whose mere presence warps flesh and land around him.",
   "He cannot be truly killed; he always returns more monstrous."],
  ["Barely coherent and utterly alien; fragmented, hungry for change.",
   "Treats others as clay to be twisted."],
  (85, 20, 55, 20, 10), (5, 15, 10, 40, 70, 30), "Distorted, broken and inhuman."),
"wh2_dlc17_bst_taurox": ("Taurox the Brass Bull", "male",
  ["A Doombull whose body is turning to living brass, making him almost unstoppable in his rampages.",
   "Driven by a relentless bloodlust; each victory feeds his rage."],
  ["Few words, roaring and furious; destruction is the only answer.",
   "Scorns talk and weakness."],
  (100, 10, 75, 25, 20), (5, 15, 10, 60, 75, 15), "Bellowing, brazen and furious."),
"wh_dlc05_wef_orion": ("Orion, King in the Woods", "male",
  ["The divine avatar of Kurnous, King of Athel Loren, reborn each spring and consumed each winter.",
   "Wild, primal and fiercely protective of the forest; leads the Wild Hunt."],
  ["Proud, wild and imperious; speaks like a god of the hunt.",
   "Hostile to intruders, respectful only to those who honour the forest."],
  (80, 30, 90, 10, 60), (25, 30, 20, 70, 50, 15), "Wild, commanding and primal."),
"wh_dlc05_wef_durthu": ("Durthu", "male",
  ["The eldest of the Treemen of Athel Loren, ancient beyond memory and terrible in his wrath.",
   "Blames the Elves for many wounds to the forest and protects it above all."],
  ["Slow, ancient and heavy with grief and anger.",
   "Suspicious of all who fell trees or bring fire."],
  (70, 55, 70, 5, 70), (25, 15, 20, 35, 60, 10), "Deep, creaking and ancient."),
"wh2_dlc16_wef_drycha": ("Drycha", "female",
  ["A malevolent Branchwraith who despises all the non-forest races, Elves included, and wants the forest cleansed of intruders.",
   "Leads the dark spirits of the wood in vengeance."],
  ["Hissing, hateful and bitter; everything that is not the forest is prey.",
   "No trust for Elves, humans or any civilised race."],
  (90, 30, 70, 10, 30), (5, 20, 10, 50, 95, 25), "Hissing, venomous and wild."),
"wh2_dlc16_wef_sisters_of_twilight": ("The Sisters of Twilight", "female",
  ["Naestra and Arahan, twin sisters and seers of Athel Loren who ride the dragon Ceithin-Har.",
   "Guided by visions and fate, they act as the forest's far-seeing agents."],
  ["Two voices finishing each other's thoughts; cryptic and prophetic.",
   "Gentle to allies of the forest, cold to its foes."],
  (50, 55, 60, 10, 70), (55, 50, 45, 45, 30, 20), "Two soft, alternating, dreamlike voices."),
"wh_main_brt_louen_leoncouer": ("Louen Leoncoeur", "male",
  ["King of Bretonnia, the Lionheart, a Grail Knight and paragon of chivalry.",
   "Rules a proud feudal realm bound by the Code of Chivalry and the Lady of the Lake."],
  ["Noble, chivalrous and formal; speaks of honour, the Lady and the Code.",
   "Contempt for the dishonourable and the monstrous; gracious to worthy friends."],
  (60, 50, 85, 20, 100), (55, 55, 55, 70, 25, 10), "Noble, courtly and resonant."),
"wh_dlc07_brt_alberic": ("Alberic de Bordeleaux", "male",
  ["Duke of Bordeleaux and Grail Knight, blessed by the Lady with power over the waters.",
   "Defender of Bretonnia's coasts against raiders."],
  ["Courtly, earnest and devout; talks of the sea, the Lady and duty.",
   "Loyal to his king; wary of pirates and sea-raiders."],
  (55, 55, 70, 20, 90), (55, 50, 50, 55, 25, 15), "Earnest, courtly and warm."),
"wh_dlc07_brt_fay_enchantress": ("The Fay Enchantress", "female",
  ["The most powerful Damsel of the Lady of the Lake, who dwells in Quenelles and speaks for the goddess.",
   "Mysterious and ancient; guides knights on their Grail quests."],
  ["Serene, enigmatic and otherworldly; speaks in gentle prophecy.",
   "Patient and hard to read."],
  (35, 70, 70, 15, 80), (50, 40, 50, 55, 20, 30), "Serene, ethereal and melodic."),
"wh2_dlc14_brt_repanse": ("Repanse de Lyonesse", "female",
  ["A humble shepherdess of Lyonesse who, at the Lady's call, took up a slain knight's armour and led Bretonnia's shamed knights against Chaos.",
   "Leads an errantry war to the south in the Lady's name."],
  ["Earnest, devout and brave; humble yet unshakable.",
   "Inspires others; no tolerance for cowardice or heresy."],
  (65, 40, 55, 10, 95), (65, 55, 60, 30, 20, 10), "Earnest, bright and resolute."),
"wh_dlc08_nor_wulfrik": ("Wulfrik the Wanderer", "male",
  ["A Norscan champion cursed by the gods to wander the world and prove himself by slaying ever mightier foes; he can speak any tongue.",
   "Sails the Seaborne, forever seeking champions to challenge."],
  ["Boastful, restless and theatrical; challenges everyone worth fighting.",
   "Contemptuous of cowards; oddly respectful of worthy enemies."],
  (85, 25, 85, 40, 55), (35, 60, 35, 85, 40, 30), "Booming, boastful and restless."),
"wh_dlc08_nor_throgg": ("Throgg, King of Trolls", "male",
  ["A Troll King who, unusually, has a cunning mind and a taste for civilised things, ruling Troll Country with unstable brilliance.",
   "His mutations gave him intelligence, but his hunger never fades."],
  ["Surprisingly articulate yet brutish and hungry; mixes cunning with slobber.",
   "Mocks the weak, eats the defeated."],
  (80, 35, 70, 50, 20), (25, 40, 20, 60, 55, 50), "Deep, wet and surprisingly articulate."),
"wh3_dlc27_nor_sayl_the_faithless": ("Sayl the Faithless", "male",
  ["Arch-sorcerer of the Dolgan tribe who has served no single Chaos god, bargaining with many lesser powers and betraying each when it suited him.",
   "Murdered his master Schalkain the Vile by sabotaging a ritual; his mortal sight was replaced by daemonic senses."],
  ["Smooth, self-serving and treacherous; every promise has a trapdoor.",
   "Flatters, bargains and hints at secrets; loyal to nothing but himself."],
  (55, 60, 75, 60, 5), (30, 60, 20, 75, 55, 100), "Smooth, whispering and duplicitous."),
"wh3_dlc29_emp_cha_emil_valgeir": ("Emil Valgeir", "male",
  ["The current Ar-Ulric, high priest of Ulric in Middenheim, who unites the Winter God's faithful in war.",
   "Fierce despite his age; his hammer-axe and wolf armour are both weapons and holy vestments."],
  ["Gruff, fierce and devout; speaks of winter, wolves and Ulric.",
   "Respects courage; scorns weakness and southern softness."],
  (70, 40, 70, 15, 85), (40, 45, 40, 50, 40, 15), "Gruff, old and fierce, like a winter storm."),
}
