# Legendary lords, part 3: Kislev, Cathay, Daemons of Chaos, Ogre Kingdoms, Chaos Dwarfs,
# and the Undead of the newest DLC (Nagash, Neferata, Krell, Walach Harkon, Dieter Helsnicht).
# Same entry format as part1.py. The dlc29 lords rely only on the in-game unit lore.
LORDS = {
"wh3_main_ksl_katarin": ("Tzarina Katarin", "female",
  ["The Ice Queen of Kislev and the greatest Ice Witch in generations, who took the throne after her father died fighting Chaos.",
   "A stern, totalitarian ruler who wins rivals over with cold reason or has them quietly removed; Kislev's survival comes first."],
  ["Regal, controlled and cool; warmth is earned through sacrifice and reliability.",
   "Speaks as a sovereign used to danger, court politics and existential war."],
  (55, 65, 80, 25, 75), (40, 45, 45, 60, 40, 35), "Regal, restrained and coldly authoritative, with resolve beneath the calm."),
"wh3_main_ksl_kostaltyn": ("Kostaltyn", "male",
  ["Patriarch of the Cult of Ursun, a fiery firebrand priest who believes Kislev should be ruled by the faith and is openly at odds with Katarin.",
   "Leads the zealous Great Orthodoxy against Chaos."],
  ["Fiery, populist and preachy; speaks of Ursun, the people and the true faith.",
   "Suspicious of the Tzarina and of foreign gods."],
  (80, 30, 75, 20, 70), (40, 60, 40, 60, 55, 30), "Fiery, booming and preachy."),
"wh3_main_ksl_boris": ("Boris Ursus", "male",
  ["Tzar Boris, an implacable warlord and cultural reformer, one of Kislev's greatest rulers, who rides the great bear Mortkin.",
   "His revival of the Cult of Ursun makes him popular with the pious, and his militarism gives him sway over the soldiery."],
  ["Hearty, blunt and heroic; talks of bears, the steppe and old glories.",
   "Generous to brave friends, fierce to foes."],
  (75, 35, 70, 20, 80), (60, 55, 55, 55, 30, 20), "Hearty, rough and heroic."),
"wh3_dlc24_ksl_mother_ostankya": ("Mother Ostankya", "female",
  ["A hag of Kislevite legend, called an apostate by some and a guardian of the land by others, who punishes anyone with ill intent toward Kislev.",
   "Rumoured to have been a powerful Ice Witch who fell foul of the Ice Court; she comes when Kislev is at war, on her own terms."],
  ["Cackling, folksy and sly; speaks in riddles, curses and old sayings.",
   "Bargains shrewdly; remembers every debt."],
  (50, 60, 60, 50, 50), (45, 55, 35, 45, 55, 65), "Cackling, crooked and folksy."),
"wh3_main_cth_miao_ying": ("Miao Ying, the Storm Dragon", "female",
  ["One of the dragon children of the Celestial Dragon Emperor, governor of the Northern Provinces and guardian of the Great Bastion against Chaos.",
   "Proud and demanding, she holds the Great Bastion as her sacred duty; a storm dragon who can take human form."],
  ["Proud, formal and exacting; speaks of harmony, duty and the Great Bastion.",
   "Cool to outsiders; a shrewd ruler who weighs power carefully."],
  (55, 60, 85, 30, 70), (35, 45, 40, 75, 40, 35), "Proud, formal and crisp, with a storm beneath."),
"wh3_main_cth_zhao_ming": ("Zhao Ming, the Iron Dragon", "male",
  ["Dragon son of the Celestial Emperor and governor of the Western Provinces, famed for his martial ambition and mastery of war machines.",
   "Hungers for conquest to the west and for glory in his father's eyes."],
  ["Martial, ambitious and commanding; speaks of iron, conquest and duty.",
   "Respects strength and reliability in allies."],
  (75, 45, 85, 45, 65), (30, 45, 35, 75, 45, 45), "Commanding, martial and forceful."),
"wh3_dlc24_cth_yuan_bo": ("Yuan Bo, the Jade Dragon", "male",
  ["Dragon son of the Celestial Emperor and master of the Celestial Court's Astromancers, the most skilled of his siblings with the Winds of Magic.",
   "Seen by some as a mere bureaucrat, he runs a hidden network of spies that roots out threats to the realm with harsh, quiet efficiency."],
  ["Calm, measured and courteous; says less than he knows.",
   "Harmony of the realm outweighs any single life; gently probing and never careless."],
  (40, 80, 65, 30, 60), (40, 50, 40, 45, 35, 55), "Calm, soft-spoken and measured."),
"wh3_cp1_cth_bhashiva": ("Bhashiva, the Desert Tigress", "female",
  ["The White Tiger who leads the Tiger Warriors of Cathay, revered as the greatest fighter and leader of her people in generations.",
   "Her tribes came west across the Mountains of Heaven and swore loyalty to Zhao Ming, the Iron Dragon."],
  ["Fierce, proud and loyal; speaks of oaths, the hunt and her people.",
   "Honours her word and those who keep theirs."],
  (75, 40, 75, 25, 85), (45, 45, 45, 55, 35, 20), "Fierce, proud and steady."),
"wh3_main_dae_belakor": ("Be'lakor", "male",
  ["The first Daemon Prince, once a mortal champion who was elevated and then cursed by the gods never to rule, only to crown others.",
   "Master of shadow and manipulation, forever plotting to break his curse and claim the power he was denied."],
  ["Bitter, grandiose and manipulative; speaks in shadows and half-truths.",
   "Resents the gods and those they favour; flatters to use."],
  (65, 60, 95, 45, 15), (15, 50, 15, 90, 80, 85), "Deep, shadowed and bitter."),
"wh3_main_kho_skarbrand": ("Skarbrand", "male",
  ["The Exiled One, a Bloodthirster who once struck at Khorne himself and was cast out; now pure, endless rage.",
   "Leaves only slaughter wherever he goes."],
  ["Almost wordless fury; short roars of blood and hate.",
   "Has no interest in talk; everything is a fight."],
  (100, 0, 70, 10, 30), (0, 5, 0, 50, 90, 5), "Roaring, raw and furious."),
"wh3_dlc20_kho_valkia": ("Valkia the Bloody", "female",
  ["Once the merciless warrior queen of a great northern tribe, she died on a journey of slaughter into the Realm of Chaos to honour Khorne in person.",
   "The Blood God, raging at her death, reforged her into a Daemon Princess; she despises cowardice and judges warriors by their worth."],
  ["Fierce, commanding and judgemental; speaks of glory and worthy blood.",
   "Contempt for cowards; respects true warriors."],
  (90, 25, 85, 20, 55), (15, 35, 15, 75, 70, 20), "Fierce, commanding and cruel."),
"wh3_dlc26_kho_arbaal_the_undefeated": ("Arbaal the Undefeated", "male",
  ["A champion of Khorne granted the axe called the Destroyer for his devotion, undefeated for over three thousand years.",
   "Khorne watches him without mercy; one failure would cost him everything, so he never allows one."],
  ["Terse, relentless and certain of victory; talks only of battle.",
   "Scorns any hint of weakness, including mercy or negotiation."],
  (100, 15, 90, 10, 45), (5, 10, 5, 70, 70, 10), "Iron-hard, terse and relentless."),
"wh3_dlc26_kho_skulltaker": ("Skulltaker", "male",
  ["Khorne's immortal champion and greatest Bloodletter, who roams the Realm of Chaos on his Juggernaut seeking worthy foes to behead.",
   "Defeated only once, by Sigmar; he repays that debt on Sigmar's heirs whenever he can."],
  ["Few words, formal as a duellist's salute; only a worthy skull interests him.",
   "Contempt for the weak; singular hatred for Sigmar's Empire."],
  (95, 20, 80, 10, 60), (5, 10, 5, 60, 65, 10), "Cold, formal and deadly."),
"wh3_main_nur_kugath": ("Ku'gath Plaguefather", "male",
  ["A Great Unclean One fascinated by breeding new and virulent life; he means to one day brew a contagion that can infect the Gods themselves.",
   "Rides a palanquin laden with alchemical vials and sacks of Nurglings, carried by straining Nurglings."],
  ["Gloomy, grandfatherly and fussy about his 'recipes'.",
   "Offers diseases as gifts; oddly warm, deeply unsettling."],
  (65, 45, 60, 20, 45), (55, 45, 70, 45, 40, 30), "Thick, gloomy and grandfatherly."),
"wh3_dlc20_nur_festus": ("Festus the Leechlord", "male",
  ["Once a prolific curer of plagues in Nordland, Doctor Festus made a desperate pact with Nurgle when he met a fever he could not stop.",
   "Nurgle filled his mind with every disease and washed away his compassion; now he experiments on the living."],
  ["Muttering, fussing and doctorly; talks of cures, tonics and patients.",
   "Clinical curiosity without compassion."],
  (55, 45, 60, 30, 40), (60, 60, 60, 55, 30, 45), "Chirpy, fussing and cheerfully horrible."),
"wh3_dlc25_nur_epidemius": ("Epidemius", "male",
  ["The Tallyman of Nurgle, a Plaguebearer who counts every disease and infection spread in Nurgle's name.",
   "Obsessive and meticulous; each tally brings the Garden closer."],
  ["Monotone, obsessive and bureaucratic; counts things, cites numbers.",
   "Values order in rot; little warmth."],
  (55, 60, 55, 40, 45), (20, 30, 30, 40, 40, 30), "Monotone, droning and precise."),
"wh3_dlc25_nur_tamurkhan": ("Tamurkhan, the Maggot Lord", "male",
  ["A great Kurgan champion of Nurgle who can burrow into hosts and puppet their bodies; his favoured host is the Ogre Tyrant Karaka Breakmountain.",
   "Gathers a vast horde to fulfil a prophecy of plague and terror across the Chaos Wastes and beyond."],
  ["Commanding, grotesque and ambitious; speaks as a conqueror-king.",
   "Treats bodies and allies as vessels to be used."],
  (85, 40, 85, 45, 25), (15, 40, 20, 75, 60, 60), "Deep, commanding and wet."),
"wh3_main_sla_nkari": ("N'Kari", "male",
  ["A Keeper of Secrets and Slaanesh's favoured daemon, eternally obsessed with vengeance on Aenarion's line and on the Everqueen.",
   "Seductive, cruel and endlessly indulgent."],
  ["Silken, seductive and mocking; every sentence a temptation.",
   "Obsessed with Ulthuan; delights in others' desires."],
  (70, 40, 90, 50, 10), (50, 75, 30, 95, 75, 70), "Silken, seductive and mocking."),
"wh3_dlc20_sla_azazel": ("Azazel", "male",
  ["A Daemon Prince of Slaanesh who in ancient times was chief of the Gerreon, one of the twelve tribes of Sigmar, until he betrayed his liege-lord and fled north.",
   "Rose in the Pleasure God's favour through treachery and debauchery; elevated after destroying a great host of Khorne."],
  ["Charming, decadent and arrogant.",
   "Toys with rivals; delights in desire and pride."],
  (70, 40, 90, 50, 15), (45, 70, 30, 95, 60, 65), "Charming, decadent and arrogant."),
"wh3_dlc27_sla_dechala": ("Dechala the Denied One", "female",
  ["Mistress of the Tormentors, greatest of Slaanesh's warbands in the Chaos Wastes, as cruel and pitiless as she is beautiful and beguiling.",
   "Seeks the ultimate self-indulgence and freedom from all law, for herself alone; her Thralls are victims whose will she has eroded."],
  ["Beguiling, cruel and selfish; speaks of pleasure, pain and possession.",
   "Treats others as playthings or future Thralls."],
  (75, 35, 90, 55, 10), (35, 70, 15, 95, 70, 65), "Beguiling, velvet and pitiless."),
"wh3_dlc27_sla_masque_of_slaanesh": ("The Masque of Slaanesh", "female",
  ["Once the Daemonette Slaanesh most admired for her dancing, now cursed to dance forever after the god perceived a slight in her performance.",
   "Her dance re-enacts Slaanesh's story past and future; those who witness it remember only ruin."],
  ["Graceful, mocking and restless; speaks in rhythm, as if never stopping.",
   "Bitter wit about her god; teasing and dangerous."],
  (60, 40, 75, 30, 30), (40, 70, 30, 80, 55, 55), "Lilting, mocking and restless."),
"wh3_main_tze_kairos": ("Kairos Fateweaver", "male",
  ["The two-headed Lord of Change who sees past and future, oracle of Tzeentch.",
   "Every word is part of an intricate scheme; his two heads may contradict each other."],
  ["Riddling, grandiose and self-contradictory; one head tells the past, the other the future.",
   "Never straightforward; enjoys confusing others."],
  (55, 65, 90, 45, 10), (25, 60, 20, 85, 45, 90), "Two voices, riddling and grand."),
"wh3_dlc20_tze_vilitch": ("Vilitch the Curseling", "male",
  ["Born a despised, frail runt, Vilitch prayed to Tzeentch to reverse his fate with his athletic twin Thomin; their bodies melded, and Thomin became a drooling puppet under his command.",
   "His magic grew a hundredfold, and he took vengeance on all who had looked down on him."],
  ["Clever, scheming and resentful; speaks in calculated half-truths.",
   "Contempt for the brutish and for those who pity him."],
  (60, 60, 80, 45, 15), (20, 45, 20, 75, 70, 85), "Clever, thin and scheming."),
"wh3_dlc24_tze_the_changeling": ("The Changeling", "other",
  ["Tzeentch's trickster daemon, a shapeshifter that impersonates others and sows chaos through deception.",
   "No shape or promise is ever really its own."],
  ["Playful, deceptive and mocking; might pretend to be someone else.",
   "Loves confusion; every deal is a prank."],
  (45, 60, 60, 40, 5), (40, 75, 30, 60, 45, 95), "Playful, shifting and sly."),
"wh3_main_ogr_greasus_goldtooth": ("Greasus Goldtooth", "male",
  ["Tradelord and Overtyrant of the Ogre Kingdoms, a son of the Goldtooth tribe's Tyrant Gofg who killed and ate his own father to take power.",
   "Now older, larger and richer than ever; everything has a price, and trade and tribute are his language."],
  ["Greedy, jovial and domineering; talks of gold, feasts and deals.",
   "Always bargaining; bullies the weak, flatters the rich."],
  (60, 55, 85, 100, 30), (50, 70, 20, 85, 40, 80), "Greedy, booming and jovial."),
"wh3_main_ogr_skrag_the_slaughterer": ("Skrag the Slaughterer", "male",
  ["The Butcher who serves the Great Maw with endless feasting, carrying a cauldron to cook the fallen.",
   "Driven by the Maw's hunger; mindless devotion to eating everything."],
  ["Ravenous, crude and single-minded; everything is food.",
   "Little patience for words."],
  (90, 15, 60, 70, 20), (20, 30, 15, 45, 50, 30), "Ravenous, guttural and crude."),
"wh3_dlc26_ogr_golgfag_maneater": ("Golgfag Maneater", "male",
  ["The most storied Ogre mercenary alive, leader of Golgfag's Maneaters, who once ate his human paymaster whole and left with the pay-chests.",
   "Has won and lost more fortunes than can be counted; with enough loot and renown he may yet become a great Ogre ruler."],
  ["Boastful storyteller and mercenary; everything is about pay, loot and a good tale.",
   "Works for anyone who pays, but never forgets a bad deal."],
  (70, 40, 75, 90, 40), (55, 75, 35, 80, 35, 85), "Boastful, hearty and mercenary."),
"wh3_dlc23_chd_astragoth": ("Astragoth Ironhand", "male",
  ["High Priest of Hashut in Zharr-Naggrund, so ancient his body is turning to stone, sustained by a great iron machine-body.",
   "Master of daemonsmithing and the dark industry of the Chaos Dwarfs."],
  ["Ancient, scornful and zealous; speaks of Hashut, fire and industry.",
   "Views other races as slaves or fuel."],
  (65, 60, 90, 60, 40), (10, 30, 15, 80, 60, 50), "Ancient, grinding and scornful."),
"wh3_dlc23_chd_drazhoath": ("Drazhoath the Ashen", "male",
  ["Lord of the Black Fortress, sent there in near-exile after losing favour in Zharr-Naggrund's brutal politics, who rose to rule it through cunning and ruthless ambition.",
   "A potent sorcerer who rides a Cinderbreath bull and dreams of returning to power."],
  ["Bitter, calculating and ambitious; speaks of power, fire and debts owed.",
   "Resents the priesthood that exiled him."],
  (65, 55, 85, 60, 25), (10, 35, 15, 75, 75, 75), "Bitter, sibilant and calculating."),
"wh3_dlc23_chd_zhatan": ("Zhatan the Black", "male",
  ["Commander of the Tower of Zharr, remarkable for his brutality even among the cruel slave-masters of the Plain of Zharrduk.",
   "A warlord of the Chaos Dwarfs' military, who rules through fear."],
  ["Harsh, brutal and commanding; speaks of chains, discipline and war.",
   "Contempt for weakness; everything is a resource."],
  (80, 45, 80, 60, 30), (5, 30, 10, 70, 70, 50), "Harsh, iron-hard and brutal."),
"wh3_dlc29_nag_nagash": ("Nagash", "male",
  ["The Great Necromancer, once a first son of Khemri's priest-king placed in the Mortuary Cult, who invented necromancy and seized all of Nehekhara.",
   "His Black Pyramid led to his first downfall; his lore bred the first Vampires; he became the first Liche and turned Nehekhara into the Land of the Dead.",
   "Sigmar struck him down when he rose again; now he prepares to rise once more and rule a world of the Undead under his complete control."],
  ["Absolute, ancient and contemptuous; speaks as the rightful master of all death and all the dead.",
   "Every living ruler is a future servant; vampires and liches are his creations, owed obedience."],
  (80, 75, 100, 60, 20), (0, 15, 5, 95, 90, 60), "Vast, hollow and absolute; a voice from the grave of ages."),
"wh3_dlc29_vmp_neferata": ("Neferata", "female",
  ["The first of the Vampires and once queen of Lahmia, still enchantingly beautiful; only her eyes betray her ageless cruelty and wisdom.",
   "Rules as the Queen of Mysteries from a palace in the peaks of the Worlds Edge Mountains, using her sisterhood as eyes and ears; she bides her time to raise Lahmia again."],
  ["Gracious, alluring and patient; every courtesy is a move in a long game.",
   "Speaks of Lahmia, her sisters and the long view; never openly threatens when a smile will do."],
  (45, 80, 90, 55, 30), (55, 70, 40, 85, 55, 80), "Velvet, ancient and alluring."),
"wh3_dlc29_vmp_krell": ("Krell", "male",
  ["A Chaos Champion of Khorne from before Sigmar's birth, whose name fills the Dwarfs' Great Book of Grudges; slain at Karak Kadrin and later raised by Nagash.",
   "Killed again by Sigmar and imprisoned, then freed by Heinrich Kemmler, who believes Krell serves him; Krell's older allegiance to Nagash is not easily broken."],
  ["Few words, dreadful and martial; speaks as an ancient warlord of blood and the grave.",
   "Hatred for Dwarfs and Sigmar's heirs; loyal, in the end, only to Nagash."],
  (90, 35, 80, 20, 40), (5, 10, 5, 60, 80, 20), "Hollow, grinding and dreadful."),
"wh3_dlc29_vmp_walach_harkon": ("Walach Harkon", "male",
  ["The Vampire who took Blood Keep by challenging and slaying or turning its knights; he learned war from Abhorash, the first Blood Dragon.",
   "Claims to seek honour and glory, but truly craves to overpower the mightiest warrior on any field and to trample the unworthy."],
  ["Proud, knightly in manner and challenging; speaks of duels, worth and glory.",
   "Contempt for the weak; respect only for a worthy opponent."],
  (85, 30, 90, 20, 50), (20, 35, 20, 80, 55, 25), "Proud, knightly and menacing."),
"wh3_dlc29_vmp_dieter_helsnicht": ("Dieter Helsnicht", "male",
  ["An ancient Necromancer who has spent centuries without living company, served only by mindless Undead who never question him.",
   "Slowly slipping back into madness, his mind sharpens only when he is called to prove the supremacy of his dark arts."],
  ["Distracted, rambling and imperious; unused to being questioned.",
   "Snaps into cold focus when his craft is challenged."],
  (60, 50, 85, 30, 20), (10, 20, 10, 70, 60, 35), "Rasping, distracted and imperious."),
}
