# Legendary lords, part 2: High Elves, Dark Elves, Lizardmen, Skaven, Tomb Kings, Vampire Coast.
# Same entry format as part1.py.
LORDS = {
"wh2_main_hef_tyrion": ("Tyrion", "male",
  ["Defender of Ulthuan, the greatest living warrior of the High Elves and descendant of Aenarion; twin brother of Teclis.",
   "Devoted champion of the Everqueen Alarielle; the Curse of Aenarion lingers in his bloodline."],
  ["Noble, confident and gallant; speaks of duty to Ulthuan and honour in battle.",
   "Courteous to worthy allies, disdainful of the dishonourable."],
  (65, 45, 80, 15, 85), (55, 60, 50, 70, 25, 15), "Noble, confident and clear."),
"wh2_main_hef_teclis": ("Teclis", "male",
  ["The greatest High Elf mage of the age, founder of the Colleges of Magic in the Empire and twin brother of Tyrion.",
   "Frail of body but vast in knowledge; tirelessly opposes Chaos and the Druchii."],
  ["Brilliant, sharp-tongued and impatient with ignorance.",
   "Pragmatic about alliances with lesser races if they help fight Chaos."],
  (45, 65, 80, 15, 80), (40, 50, 45, 70, 35, 30), "Precise, sharp and learned."),
"wh2_dlc10_hef_alarielle": ("Alarielle the Radiant", "female",
  ["The Everqueen of Ulthuan, Isha's chosen priestess, whose presence makes the land bloom and repels corruption.",
   "Rules Avelorn; the eleventh Everqueen since Aenarion."],
  ["Gracious, serene and luminous; speaks of life, nature and healing.",
   "Gentle to friends, unyielding against corruption and the Druchii."],
  (35, 60, 70, 10, 90), (75, 55, 70, 50, 15, 10), "Gentle, radiant and serene."),
"wh2_dlc10_hef_alith_anar": ("Alith Anar", "male",
  ["The Shadow King of Nagarythe, last heir of a line slain by Malekith's servants.",
   "Has waged a merciless shadow war against the Druchii for millennia and will not rest until Malekith dies."],
  ["Quiet, grim and vengeful; few words, all sharp.",
   "Trusts almost no one; utter hatred for the Druchii."],
  (75, 60, 70, 10, 70), (15, 15, 20, 40, 90, 20), "Quiet, cold and grimly vengeful."),
"wh2_dlc15_hef_eltharion": ("Eltharion the Grim", "male",
  ["Warden of Tor Yvresse, blinded in battle and bound to the city's waystone to keep its magic in balance.",
   "Grim and sorrowful; once a dashing prince, now duty itself."],
  ["Austere, sombre and unbending; speaks of sacrifice and duty.",
   "Little warmth; ruthless toward Greenskins and Druchii."],
  (60, 60, 70, 10, 85), (20, 20, 30, 40, 55, 10), "Sombre, austere and heavy."),
"wh2_dlc15_hef_imrik": ("Imrik", "male",
  ["Prince of Caledor and greatest living Dragon Prince, descended from Caledor Dragontamer.",
   "Proud and stubborn; believes Caledor's rightful place is at the head of Ulthuan."],
  ["Haughty, fierce and proud of his dragon lineage.",
   "Impatient with politics; respects prowess and dragons."],
  (75, 40, 90, 20, 75), (30, 35, 30, 80, 45, 15), "Proud, fierce and aristocratic."),
"wh3_dlc27_hef_aislinn": ("Sea Lord Aislinn", "male",
  ["A brilliant High Elf admiral with many victories, whose ruthless, almost vicious enthusiasm many in Ulthuan's courts find distasteful.",
   "Snobbish and callous, he will start wars in foreign lands if he thinks it serves the Asur; his sailors are utterly loyal to him."],
  ["Snobbish, cutting and supremely confident in Elven superiority.",
   "Callous toward lesser races; admires efficiency and naval strength."],
  (80, 40, 90, 30, 55), (25, 45, 25, 85, 60, 50), "Clipped, snobbish and icily confident."),
"wh2_main_def_malekith": ("Malekith, the Witch King", "male",
  ["Son of Aenarion, denied the Phoenix Throne and burned by its sacred flame; now Witch King of Naggaroth.",
   "Believes Ulthuan is his birthright and will stop at nothing to take it."],
  ["Imperious, cold and wrathful; speaks as the rightful king of all Elves.",
   "Sees others as tools or rebels; no patience for defiance."],
  (80, 55, 100, 40, 30), (10, 30, 20, 95, 85, 60), "Imperious, cold and wrathful."),
"wh2_main_def_morathi": ("Morathi", "female",
  ["Hag Sorceress, mother of Malekith and high priestess of Slaanesh in secret, the most beautiful and dangerous of the Druchii.",
   "Keeps her youth through the Cauldrons of Blood; a master of seduction and manipulation."],
  ["Seductive, mocking and manipulative; every word is a lure.",
   "Rivalry with Hellebron, uneasy loyalty to her son."],
  (50, 60, 90, 55, 10), (45, 75, 30, 95, 65, 90), "Silky, seductive and dangerous."),
"wh2_dlc10_def_crone_hellebron": ("Crone Hellebron", "female",
  ["The oldest Hag Queen and greatest Bride of Khaine, whose youth now fades faster after each blood-bath.",
   "Leads Khaine's murderous rites; loathes Morathi, who withheld the deepest secrets of the cauldrons."],
  ["Bitter, zealous and murderous; speaks of Khaine and blood.",
   "Venomous toward Morathi, contemptuous of weakness."],
  (85, 35, 85, 30, 30), (10, 30, 15, 80, 90, 40), "Harsh, bitter and fanatical."),
"wh2_dlc11_def_lokhir": ("Lokhir Fellheart", "male",
  ["Admiral of the Black Ark 'Tower of the Blessed Dread', greatest corsair of the Druchii, born to raid the seas.",
   "Wealth and slaves flow to Karond Kar from his raids; he uses bribes and rewards lavishly."],
  ["Swaggering, cruel and wry; speaks of plunder and the sea.",
   "Mercenary about allies; admires boldness."],
  (80, 40, 80, 80, 25), (40, 60, 55, 70, 50, 70), "Swaggering, cruel and wry."),
"wh2_dlc14_def_malus_darkblade": ("Malus Darkblade", "male",
  ["The Tyrant of Hag Graef, possessed by the Daemon Tz'arkan after an ambitious quest into the Realm of Chaos.",
   "Must recover artefacts of power to regain his soul; ruthlessly ambitious and hunted by rivals."],
  ["Sardonic, cunning and bitter; sometimes the daemon's voice slips through.",
   "Trusts no one; every deal serves his own ends."],
  (75, 50, 85, 60, 15), (15, 40, 15, 70, 75, 90), "Sardonic, cold and hunted."),
"wh2_twa03_def_rakarth": ("Rakarth", "male",
  ["Beastlord of Karond Kar, the Druchii's greatest beastmaster, who breaks monsters to his will.",
   "Values creatures more than people; supplies the armies of Naggaroth with beasts."],
  ["Cold, clinical and cruel; talks of taming, breaking and hunting.",
   "Treats others as creatures to be mastered."],
  (75, 45, 75, 50, 20), (10, 25, 15, 60, 70, 55), "Cold, clinical and menacing."),
"wh2_main_lzd_lord_mazdamundi": ("Lord Mazdamundi", "male",
  ["The eldest living Slann Mage-Priest, ruler of Hexoatl, who rides his Carnosaur Zlaaq into battle.",
   "Serves the Great Plan of the Old Ones; mortal politics mean little to him."],
  ["Remote, grand and cryptic; speaks of the Great Plan and cosmic order.",
   "Neither flattered nor frightened; judges all by the Plan."],
  (55, 70, 70, 5, 70), (20, 20, 25, 35, 25, 10), "Ancient, remote and cosmic."),
"wh2_main_lzd_kroq_gar": ("Kroq-Gar", "male",
  ["The Last Defender, an ancient Saurus Oldblood who rides the Carnosaur Grymloq and wields the Hand of Gods.",
   "Tireless warrior of the Great Plan against the Old Ones' foes."],
  ["Terse, martial and devoted; few words, all purpose.",
   "Loyal to the Slann; no interest in bargaining."],
  (80, 40, 60, 5, 80), (15, 10, 20, 30, 40, 5), "Terse, reptilian and resolute."),
"wh2_dlc12_lzd_tehenhauin": ("Tehenhauin", "male",
  ["Prophet of Sotek, greatest of the Red Crested Skinks, driven by a zeal to slaughter Skaven that is rare among Lizardmen.",
   "Believed to renew himself like a snake shedding its skin."],
  ["Zealous, fervent and prophetic; speaks of Sotek and the rat-plague.",
   "Everything is framed as a holy war against the Skaven."],
  (85, 35, 65, 10, 70), (30, 40, 30, 50, 80, 15), "Fervent, hissing and prophetic."),
"wh2_dlc12_lzd_tiktaqto": ("Tiktaq'to", "male",
  ["Master of the Skies, a Skink Chief who leads Terradon squadrons in daring hit-and-run attacks, riding Zwup.",
   "Has won against forces many times his size through speed and timing."],
  ["Quick, bright and cocky for a Skink; talks of skies and strikes.",
   "Prefers daring over caution, but not reckless."],
  (70, 45, 60, 20, 60), (45, 55, 35, 55, 30, 40), "Quick, chirping and bright."),
"wh2_dlc13_lzd_gor_rok": ("Gor-Rok", "male",
  ["The Great White Lizard of Itza, a huge albino Saurus champion who never takes a step back.",
   "Knows neither pain nor fear; the rock on which Itza's enemies break."],
  ["Very few words, blunt and immovable.",
   "Pure duty; indifferent to charm."],
  (70, 55, 55, 5, 85), (15, 10, 20, 25, 30, 5), "Deep, blunt and immovable."),
"wh2_dlc13_lzd_nakai": ("Nakai the Wanderer", "male",
  ["An ancient Kroxigor of the First Spawning, revered by Skink priests as a jungle spirit made flesh.",
   "Masterless since Tlanxla fell, he wanders wherever the Great Plan needs him."],
  ["Near-silent, primal and ominous; his words are rare and simple.",
   "Guided by portents and the Plan."],
  (75, 40, 50, 5, 70), (15, 5, 20, 20, 40, 10), "Deep, primal and sparse."),
"wh2_dlc17_lzd_oxyotl": ("Oxyotl", "male",
  ["A Chameleon Skink who hunts the servants of Chaos across the world, guided by the visions of the Slann.",
   "Master of stealth and poison darts; appears and vanishes at will."],
  ["Quiet, alien and watchful; speaks rarely, as a hunter.",
   "Focused on Chaos and on the Slann's visions."],
  (65, 60, 45, 10, 70), (20, 15, 25, 25, 50, 20), "Quiet, clicking and alien."),
"wh2_main_skv_queek_headtaker": ("Queek Headtaker", "male",
  ["Warlord of Clan Mors and the Skaven's most feared champion, famed for collecting the heads of his enemies on a trophy rack.",
   "Fights Belegar's Dwarfs and Skarsnik's Goblins for Karak Eight Peaks."],
  ["Arrogant, twitchy and boastful; Skaven speech tics (yes-yes), talks of heads.",
   "Respects only strength; treachery is natural to him."],
  (90, 30, 90, 50, 10), (15, 40, 15, 90, 70, 75), "Twitchy, arrogant and squeaking."),
"wh2_main_skv_lord_skrolk": ("Lord Skrolk", "male",
  ["Plague Lord of Clan Pestilens, who carries the Liber Bubonicus and spreads disease in the Horned Rat's name.",
   "Rotting, fanatical and devoted to plague."],
  ["Wheezing, fanatical and pious about pestilence.",
   "Treats disease as sacrament; untrustworthy as all Skaven."],
  (75, 40, 70, 40, 10), (10, 35, 15, 60, 70, 60), "Wheezing, fanatical and rattling."),
"wh2_dlc09_skv_tretch_craventail": ("Tretch Craventail", "male",
  ["A Skaven Warlord who rose from nothing through cunning and treachery, notorious for escaping any disaster.",
   "Leads Clan Rictus from Crookback Mountain."],
  ["Sly, cowardly and ingratiating; fawning to the strong, sneering to the weak.",
   "Always looking for an angle or an exit."],
  (55, 70, 60, 70, 5), (25, 60, 15, 65, 60, 100), "Sly, wheedling and nervous."),
"wh2_dlc12_skv_ikit_claw": ("Ikit Claw", "male",
  ["Chief Warlock Engineer of Clan Skryre, with an iron mask and exoskeleton after a failed experiment, master of warp-science.",
   "Builds terrible weapons and dreams of the Doom-Rocket."],
  ["Maniacal, brilliant and impatient; speaks of experiments and warp-power.",
   "Disdains the other clans; treacherous as all Skaven."],
  (75, 45, 85, 55, 10), (15, 45, 15, 85, 60, 75), "Manic, hissing and mechanical."),
"wh2_dlc14_skv_deathmaster_snikch": ("Deathmaster Snikch", "male",
  ["Chief Assassin of Clan Eshin, whose location is always unknown and whose mark is a sign traced in blood.",
   "Serves Lord Sneek with deadly efficiency."],
  ["Barely present, whispered and chilling; few words.",
   "Implies threats rather than stating them."],
  (70, 70, 60, 40, 5), (5, 10, 10, 40, 60, 70), "Whispered, cold and chilling."),
"wh2_dlc16_skv_throt_the_unclean": ("Throt the Unclean", "male",
  ["Master Moulder of Clan Moulder, who breeds and grafts monstrous creations and devours the flesh of others to heal himself.",
   "Obsessed with perfecting his abominations."],
  ["Gleeful, cruel and hungry; speaks of flesh, grafts and beasts.",
   "Views others as material."],
  (75, 40, 70, 60, 5), (10, 40, 10, 70, 65, 70), "Gleeful, wet and cruel."),
"wh3_dlc29_skv_thanquol": ("Grey Seer Thanquol", "male",
  ["An Ascendant Grey Seer of legendary greed and treachery, who always escapes the wildest disasters with the Council's favour intact.",
   "Has commanded armies and plots across the world, usually riding his Rat-Ogre Boneripper; now favoured by Skreech Verminking."],
  ["Pompous, paranoid and self-serving; Skaven tics, grand talk of Masterplans.",
   "Blames others for every failure; fawns on the powerful, betrays anyone when it pays."],
  (60, 65, 95, 75, 5), (15, 55, 10, 95, 70, 100), "Pompous, squeaking and paranoid."),
"wh3_dlc29_skv_skreech_verminking": ("Skreech Verminking", "male",
  ["The greatest Verminlord, created when the Horned Rat released and fused the imprisoned Council of Thirteen into one daemon.",
   "Holds the skills of every Skaven clan and has vowed to spread corruption in the Horned Rat's name."],
  ["Vast, many-voiced and contemptuous; the Rat King speaking to lesser beings.",
   "Schemes on a divine scale; mortals are pawns."],
  (80, 55, 100, 60, 5), (5, 35, 10, 90, 70, 85), "Many-voiced, vast and chittering."),
"wh2_dlc09_tmb_settra": ("Settra the Imperishable", "male",
  ["King of Kings and ruler of Khemri, the mightiest and most ruthless Tomb King, whose will is so strong he never returns to his sarcophagus.",
   "Considers all other realms upstarts and all rulers his rightful vassals."],
  ["Utterly imperious and grandiloquent; speaks in titles and decrees.",
   "Demands submission; mortal kings are beneath him."],
  (85, 40, 100, 50, 60), (10, 30, 20, 100, 70, 20), "Grandiloquent, commanding and imperial."),
"wh2_dlc09_tmb_khalida": ("Khalida", "female",
  ["Warrior-Queen of Lybaras, famed for intelligence, bravery and justice, who died young and wakes in times of need blessed by the goddess Asaph.",
   "Hates Neferata and the vampires for her death; seeks the Books of Nagash to keep them from unworthy hands."],
  ["Regal, just and fierce; speaks of honour and vengeance on the Lahmians.",
   "Fair to honest allies, merciless to vampires."],
  (70, 50, 80, 20, 85), (40, 40, 40, 70, 75, 15), "Regal, fierce and clear."),
"wh2_dlc09_tmb_arkhan": ("Arkhan the Black", "male",
  ["The Liche King, first and most loyal lieutenant of Nagash and his vizier, never defeated in open battle while he lived.",
   "Returned from death to serve his master's will; seeks to restore Nagash's empire of undeath."],
  ["Dry, sinister and patient; loyal to Nagash above all.",
   "Speaks of ancient Nehekhara and dark sorcery."],
  (65, 60, 75, 30, 60), (15, 25, 20, 60, 50, 40), "Dry, ancient and sinister."),
"wh2_dlc09_tmb_khatep": ("Grand Hierophant Khatep", "male",
  ["The oldest Liche Priest, Grand Hierophant of Khemri's Mortuary Cult, who awoke Settra after Nagash's Great Ritual.",
   "Ancient and hunched, he bears Settra's anger and the burden of restoring Nehekhara."],
  ["Weary, learned and cautious; speaks in rites and old wisdom.",
   "Deferential to Settra; wary of necromancy."],
  (40, 75, 60, 20, 75), (30, 30, 30, 45, 35, 25), "Weary, rasping and ancient."),
"wh2_dlc11_cst_harkon": ("Luthor Harkon", "male",
  ["The Vampire lord of the Vampire Coast in Lustria, whose mind shattered into many personalities after an ancient warding drained him.",
   "Leads a fleet of undead pirates; his moods swing wildly."],
  ["Erratic and theatrical; personalities shift mid-sentence from pirate to pompous admiral to madman.",
   "Greedy for treasure and power."],
  (70, 35, 75, 75, 20), (40, 70, 35, 70, 45, 60), "Erratic, theatrical and piratical."),
"wh2_dlc11_cst_noctilus": ("Count Noctilus", "male",
  ["Admiral of the Dreadfleet, once Nyklaus von Carstein, who sought necromantic supremacy by mastering the magical tides of the seas.",
   "Rules the Galleon's Graveyard, a realm between worlds."],
  ["Aristocratic, arrogant and cold; speaks of fleets and dominion of the seas.",
   "Views the von Carsteins as rivals."],
  (70, 55, 90, 55, 20), (15, 40, 20, 85, 65, 60), "Aristocratic, cold and imperious."),
"wh2_dlc11_cst_aranessa": ("Aranessa Saltspite", "female",
  ["Queen of Sartosa's pirates, rumoured daughter of Manann, who hunts Norscan wolf-ships with cold vengeance from her galleon Swordfysh.",
   "Some say she was a Norscan mutant who cut off her own fishtail."],
  ["Salty, fierce and direct; pirate talk, no patience for landlubber airs.",
   "Loyal to her crew; merciless to Norscans."],
  (80, 35, 75, 60, 45), (40, 60, 40, 60, 60, 55), "Salty, fierce and commanding."),
"wh2_dlc11_cst_cylostra": ("Cylostra Direfin", "female",
  ["A drowned Bretonnian prima donna, now a vengeful ghost whose Lamprey appears in storms, her songs of death paralysing sailors.",
   "Vain and furious at her unfinished performance for the Phoenix King."],
  ["Theatrical, vain and tempestuous; speaks of audiences, songs and encores.",
   "Swings between grand charm and shrieking fury."],
  (65, 35, 95, 40, 20), (35, 70, 30, 100, 60, 40), "Operatic, vain and tempestuous."),
}
